[font]
  # Base font size in points
  size = 11.0

  # Normal (roman) font face with emoji fallback
  normal = { family = "Anonymous Pro", style = "Regular" }

  # Bold face (falls back to `normal` family if unspecified)
  bold = { family = "Anonymous Pro", style = "Bold" }

  # Italic face
  italic = { family = "Anonymous Pro", style = "Italic" }

  # Bold‑Italic face (optional)
  bold_italic = { family = "Anonymous Pro", style = "Bold Italic" }

  # Add fallback fonts for symbols/emojis
  builtin_box_drawing = true

  # Character spacing adjustments (optional)
  offset = { x = 1, y = 1 }
  glyph_offset = { x = 0, y = 0 }

[colors.primary]
background = "#0a0a0a"  # Midnight Black
foreground = "#eaeaea"  # Moonlit White

[colors.normal]
black = "#2e2e2e"      # Ash Gray
red = "#aa0000"        # Blood Red
green = "#4f5b93"      # Chalice Blue
yellow = "#bfa06d"     # Blood Echo Gold
blue = "#4f5b93"       # Chalice Blue
magenta = "#7a5ccc"    # Beast Purple
cyan = "#4f5b93"       # Chalice Blue
white = "#a0a0a0"      # Fog Silver

[colors.bright]
black = "#666666"      # Tombstone Gray
red = "#ff5555"        # Crimson Echo
green = "#4f5b93"      # Chalice Blue
yellow = "#bfa06d"     # Blood Echo Gold
blue = "#4f5b93"       # Chalice Blue
magenta = "#7a5ccc"    # Beast Purple
cyan = "#4f5b93"       # Chalice Blue
white = "#eaeaea"      # Moonlit White

[window]
opacity = 0.45
padding = { x = 15, y = 15 }
decorations = "None"
startup_mode = "Windowed"
dynamic_title = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
unfocused_hollow = true

[terminal]
osc52 = "CopyPaste"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[env]
TERM = "alacritty"
